[build]
  command = "pip install -r requirements.txt"
  publish = "/"

[build.environment]
  PYTHON_VERSION = "3.10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"

[dev]
  framework = "#custom"
  command = "python app.py"
  port = 5002
  targetPort = 5002
